### ISSUE TITLE
Enhance Menu Generation

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/parere#4]
The menu generation can be extracted into its own include (vendor). Than we add a possibility to define buttons and add icons to the navigation item.

**Branch:** enhancement-001

## Tasks

- [x] Extract menu generation into its own include.
- [x] Add possibility to define buttons for menu item.
- [x] Add possibility to define icons used in menu item.
